name:  ci/cd pipeline to deploy to tomcat

on:
  push:
     branches:
       - master  # Runs pipeline onlu when pushing to master branch
jobs:
   build-deploy:
      runs-on: ubuntu-latest

      steps:
        # Checkout repo
        - name: Checkout code 
          uses: actions/checkout@v3

        # Set up java 
        - name: set up jdk 11
          uses: actions/setup-java@v3
          with: 
            distribution: 'temurin'
            java-version:  '11'
            
        #validate with  maven(update)
        - name: validate the code
          run: mvn validate
          
        #compile with  maven(update)
        - name: compile the code
          run: mvn compile
          
         #test with  maven(update)
        - name: test the code
          run: mvn test
          
          #package with  maven(update)
        - name: package the code
          run: mvn package
        
          #verify the war file
        - name: verify 
          run: ls -l target/   

         #Deploy to tomcat
        - name: Deploy to tomcat
          run: |
                 curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
                  -T target/TrainBook-1.0.0-SNAPSHOT.war \
                  "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"
