name: CI/CD with SonarQube

on:
  push:
    branches:
      - main  # Run on pushes to main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java (required for Maven)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build the Maven project
      - name: Build with Maven
        run: mvn clean install -B

      # 5. Run SonarQube analysis
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Set this secret in your repo
        run: mvn sonar:sonar \
             -Dsonar.projectKey=TRAINTICKET \
             -Dsonar.host.url=http://51.20.182.104:9000 \
             -Dsonar.login=$SONAR_TOKEN


