name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
           distribution: temurin       # JDK distribution (temurin, zulu, corretto, etc.)
           java-version: 11


      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
           -Dsonar.projectKey=TRAINTICKET
           -Dsonar.host.url=http://51.20.182.104:9000


