name: SonarQube Analysis

on:
  push:
    branches: 
    - master
 
jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: validate with maven
        run: mvn validate

      - name: compile with maven
        run: mvn compile

      - name: test with maven
        run: mvn test

      - name: package with maven
        run:  mvn package 

      - name: verify WAR file
        run: ls -lh target/

      - name: sonarqube code quality
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=train-ticket-reservation \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
